brunopulis/awesome-a11y

README.md

Tuts+ is creating a series of posts on web accessibility for Wordpress.
I think it's not finished yet, but it's nice to have it from now since the content is already good :)

Adds tuts+ learning guide for WP

---

README.md

Fala Bruno,
Um ótimo artigo falando sobre acessibilidade.
Valeu.

New Article About Accessibility

---

README.md

add some links about audit and a reference to a set of articles from simplyaccessible.com

add some audit tools and articles

---

README.md

Hi, I found these examples really helpful and easily implementable.
So I thought, why not. ;)

Add resource link with practical examples

---

README.md

Hello. I think it is better for accessibility if the links are ordered alphabetically.

Alphabetize links

---

README.md

Hey. This PR fixes all the typos related to `contributing` that I could find, inspired by your commit.

Fix remaining contributing typos

---

README.md

substantial moved their blog to http://staging.substantial.com

Update How I Audit a Website for Accessibility link

---

README.md

This hands-on resource for all UXers is a project guide to UX design and content strategy that explores the relationship through a website project.

Added free PDF of gathercontent.com

---

README.md

Figured I'd add mine :)
Hope it's okay!

Add accessibility debt presentation

---

README.md

webcomponent for skip to content added

---

README.md

Hi,
I propose these projects, 9 examples of accessible components: http://a11y.nicolas-hoffmann.net/
Hope you will be interested in.
Kind regards,
Nicolas

Add accessibility section (jQuery plugins)

---

README.md

adding https://www.aslint.org/ to the Development Testing and Validators section

add new tool to the list

---

README.md

Awesome tools to test your site / app’s colors through several colorblindness filters.
https://michelf.ca/projects/sim-daltonism/
https://github.com/michelf/sim-daltonism/

add sim daltonism

---

README.md

Adding https://www.w3.org/TR/UNDERSTANDING-WCAG20/
It is a powerful document

Adding Understanding WCAG 2.0

---

README.md

Trello accessibility cards generator

---

README.md

Look like this account is not longer active.

remove @PayPalInclusive from the companies list

---

README.md

http://inclusive-components.club/

Add Inclusive Components

---

README.md

This is an article on how developers can use aXe to automatically check and report on potential accessibility problems in their sites and apps

Add aXe tutorial

---

README.md

@MylesBorins mentioned this talk as recommended in the [offline camp berlin](http://offlinefirst.org/camp/)

Add a new talk

---

README.md

Links added to: Guides, Courses, Articles and Videos, Books, Development Testing and Validators, Other Resources and Talks sections

Adding a variety of links in multiple sections

---

README.md

I am assuming permission to use the image has been secured already.

Adding credit to the image

---

README.md

- Added Ember A11y Testing to "Developing Testing and Validators" section
- Put "Other Resources" section in alphabetical order (as per the contrib guidelines)
- Added Ember A11y and Ember A11y Landmarks to "Other Resources" section
- Added a talk in the "Talks" section

Adding Ember.js resources to this awesome list!

---

README.md

Fixed the extra spaces! Thanks!

updated to add Ember resources

---

topics/assistive-technology.md

ChromeVox is a built-in screen reader in Chrome OS: https://support.google.com/chromebook/answer/7031755?hl=en

Add Chrome OS to the list of ChromeVox OS list

---

topics/articles.md
topics/meetups.md

Just added a few links for #hacktober! Please note that I think I removed a trailing line on both docs, hence it looking like i edited existing links. Thanks!

Add 2 W3C links to articles and portland meetup link to meetups

---

topics/courses.md
topics/meetups.md
topics/people.md
topics/talks.md

Get ready, I'll do some contributions in this AWESOME project! 
Congrats and thanks for it! <3

First of many

---

topics/other-resources.md

Add dos and don'ts for accessibility and aphasia + WCAG 2.1 Map

Add posters

---

topics/articles.md
topics/companies.md
topics/other-resources.md

Contributions to Organizations and Companies, Articles and Other Resources

---

topics/books.md

The book focus on accessibility of web forms. Related to #66 .

Introducing the fresh book by Smashing Magazine "Form Design Patterns"

---

README.md
topics/assistive-technology.md

This PR changes:
- change "Screen Readers" to "Assistive Technology" in README to be more broad for softwares regarding accessibility
- add a section with OSK (on-screen keyboard) technologies in `topics/assistive-technology.md`

add OSK software

---

topics/validators.md

ESLint: eslint-plugin-vue-a11y
Vue.js: vue-a11y-utils, vue-axe

Adding Vue.js and ESLint plugins

---

topics/specification.md

The link is the same, but the final rec was published in June.

Remove Draft From WCAG 2.1

---

topics/other-resources.md

- Add Accessible react component that help devs to add skip navigation links in react websites.

Add skip-links component

---

topics/other-resources.md

Wasn't sure what section was best, but this is a nice resource to answer questions about 'who is affected'.

Add WAI User Personas Page

---

topics/companies.md

Oswald Labs is an award-winning accessibility technology company.

Add Oswald Labs

---

topics/articles.md

Oi Bruno :)
I added an article about Accessibility in general but with some nice tips in React (I think a lot of this a11y knowledge is missing from the React community). Disclaimer: I'm the author of the article.
PS: Obrigado por criar esta lista, aprendi tanta coisa com as coisas que estão aqui listadas.

Added Accessibility and React article

---

topics/assistive-technology.md

Updated the tables to break up data into more columns (like cost and platform), making them easier to scan through.
Added "Windows On-Screen Keyboard" to list of OSKs.

Assistive technologies

---

README.md
topics/assistive-technology.md
topics/companies-and-organizations.md
topics/companies.md

1. Changing file name to match title within document ("Companies and organizations"), with link update to main Table of Contents.
2. Adding links to websites for each company/organization.
3. Adding a new column with very brief descriptions of what each company does - likely incomplete but hopefully not inaccurate.
4. Updating or removing a few outdated or incorrect link URLs. (https://github.com/brunopulis/awesome-a11y/commit/48078914df16500bed73d33e47ac259fc1c851aa)
For some reason the updates to `assistive-technology.md` from my other PR made their way in this. Must have goofed up something with Git along the way on my end. By reviewing and merging in PR #102, this should resolve itself on its own.

Companies and organizations

---

topics/guides.md

Totally superficial, but just making the table formatting match what's used on other pages.

Guides - normalizing table formatting

---

topics/companies-and-organizations.md
topics/people.md

I added one person and two organizations that contribute to a web more affordable.

Adding @claumartin, Audima and Hand Talk

---

topics/articles-and-videos.md

Adding a nice blogpost by David MacDonald about WAI Aria.

Add Blogpost by David MacDonald

---

README.md
topics/tools.md

This would close #110. There are definitely more tools but they're the ones I had off the top of my head.

Add Tools section

---

topics/articles-and-videos.md
topics/courses.md
topics/laws.md
topics/specification.md
topics/talks.md

This PR includes some resources from my accessibility list (including my own contributions)

Include more resources

---

topics/courses.md

feat(course): add course Introducao a Audiodescricao

---

topics/other-resources.md
topics/talks.md
topics/validators.md

fix(broken-links): fixes broken links

---

topics/guides.md

add a brasilian guide: eMAG - Modelo de Acessibilidade em Governo Eletrônico

add eMAG guide

---

topics/validators.md

This is a request to add my open-source browser extension that recently got some positive feedback from early users: https://chrome.google.com/webstore/detail/aria-devtools/dneemiigcbbgbdjlcdjjnianlikimpck

Add ARIA DevTools

---

topics/validators.md

- Just noticed the link was broken 🙂
- Resolves #134

Fix Checka11y.css link

---

topics/guides.md

Adding an interesting guideline used from BBC devs & qas: https://github.com/bbc/bbc-a11y

Adding BBC a11y Guideline

---

topics/companies-and-organizations.md
topics/other-resources.md

I have created an awesome-list of technology companies in Japan that are working on or promoting accessibility.
https://github.com/yamanoku/awesome-japanese-a11y-companies

Add: awesome-japanese-a11y-companies

---

README-pt-br.md

feat: add translation to pt-br

---

topics/tools.md

Add NPM packages: 
- accessibility-checker
- cypress-accessibility-checker
add web extensions
- Chrome browser extension : IBM equal access accessibility checker
- Firefox browser add-on: IBM equal access accessibility checker

add resources to tools list

---

topics/tools.md

Adds two resources to the tools list:
- [Guidepup](https://github.com/guidepup/guidepup) - Screen reader driver for test automation.
- [Virtual Screen Reader](https://github.com/guidepup/virtual-screen-reader) - Virtual screen reader driver for unit test automation.

feat: add Guidepup and Virtual Screen Reader tools

---

topics/guides.md

There is no precent for resources with multiple languages, so I have just wrote "MULTIPLE". 
Feel free to edit it.

Added UK services

---

topics/articles-and-videos.md

The article on this pull request introduces two Windows Accessibility APIS: Microsoft Active Accessibility (MSAA) and Microsoft UI Automation (UIA), and illustrates examples on where they are used and some complementary material. There are two more native accessibility APIS I know in use on Windows: IAccessible2 and Java Access Bridge. I currently did not find an article for them, but this article might help someone when choosing between MSAA and UIA.

feat: add Microsoft Active Accessibility and UI Automation compared article

---

topics/people.md

I'm not on twitter anymore, but I am still active elsewhere on social media, so I thought I'd submit a PR to update my link.

Update people.md for Melanie Sumner
